/**
 * MCP Bridge Extension for pi-coding-agent.
 *
 * Reads a Nix-generated manifest (`~/.pi/agent/mcp-manifest.json`) and spawns
 * each listed MCP server as a child process. Tool calls from the LLM are
 * translated to MCP JSON-RPC requests and results are relayed back.
 *
 * The manifest is generated by `helpers/_mcp-transforms.nix` and installed to
 * `~/.pi/agent/mcp-manifest.json` by `files.nix`.
 */
import { Type } from "@mariozechner/pi-ai";
import { defineTool, type ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { spawn, type ChildProcess } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { createConnection } from "node:net";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface McpManifest {
  servers: McpServerEntry[];
}

interface McpServerEntry {
  name: string;
  type: "local" | "remote";
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
}

interface JsonRpcRequest {
  jsonrpc: "2.0";
  id: number;
  method: string;
  params?: Record<string, unknown>;
}

interface JsonRpcResponse {
  jsonrpc: "2.0";
  id: number;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
}

interface McpTool {
  name: string;
  description?: string;
  inputSchema?: Record<string, unknown>;
}

interface McpToolsResult {
  tools: McpTool[];
}

// ---------------------------------------------------------------------------
// Stdio transport — speaks JSON-RPC over stdin/stdout with an MCP server
// ---------------------------------------------------------------------------

class StdioTransport {
  private proc: ChildProcess | null = null;
  private buffer = "";
  private pending = new Map<number, {
    resolve: (resp: JsonRpcResponse) => void;
    reject: (err: Error) => void;
  }>();
  private nextId = 1;
  private initialized = false;
  readonly name: string;

  constructor(
    name: string,
    private command: string,
    private args: string[],
    private env: Record<string, string>,
  ) {
    this.name = name;
  }

  async start(): Promise<void> {
    this.proc = spawn(this.command, this.args, {
      stdio: ["pipe", "pipe", "pipe"],
      env: { ...process.env, ...this.env },
    });

    this.proc.stdout!.on("data", (chunk: Buffer) => {
      this.buffer += chunk.toString("utf8");
      this.drain();
    });

    this.proc.stderr!.on("data", () => {
      // Suppress all MCP server stderr — startup banners pollute pi's TUI.
      // Real errors surface via failed JSON-RPC responses.
    });

    this.proc.on("error", () => {
      // Suppress — errors surface via failed JSON-RPC responses.
    });

    this.proc.on("exit", () => {
      this.proc = null;
      // Reject all pending requests
      for (const [id, { reject }] of this.pending) {
        reject(new Error(`MCP server ${this.name} exited`));
        this.pending.delete(id);
      }
    });

    // MCP initialization handshake
    await this.sendRequest("initialize", {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "pi-mcp-bridge", version: "0.1.0" },
    });
    // Send initialized notification (no response expected)
    this.sendNotification("notifications/initialized", {});
    this.initialized = true;
  }

  async listTools(): Promise<McpTool[]> {
    const resp = await this.sendRequest("tools/list", {});
    return (resp.result as McpToolsResult).tools ?? [];
  }

  async callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
    const resp = await this.sendRequest("tools/call", { name, arguments: args });
    if (resp.error) {
      throw new Error(`MCP tool error [${this.name}/${name}]: ${resp.error.message}`);
    }
    return resp.result;
  }

  async stop(): Promise<void> {
    if (!this.proc) return;
    try {
      this.sendNotification("notifications/cancelled", {});
    } catch {
      // best effort
    }
    this.proc.kill("SIGTERM");
    this.proc = null;
  }

  private sendRequest(method: string, params: Record<string, unknown>): Promise<JsonRpcResponse> {
    return new Promise((resolve, reject) => {
      if (!this.proc?.stdin?.writable) {
        reject(new Error(`MCP server ${this.name} not running`));
        return;
      }
      const id = this.nextId++;
      const msg: JsonRpcRequest = { jsonrpc: "2.0", id, method, params };
      this.pending.set(id, { resolve, reject });
      const data = `Content-Length: ${Buffer.byteLength(JSON.stringify(msg))}\r\n\r\n${JSON.stringify(msg)}`;
      this.proc.stdin.write(data);
    });
  }

  private sendNotification(method: string, params: Record<string, unknown>): void {
    if (!this.proc?.stdin?.writable) return;
    const msg = { jsonrpc: "2.0" as const, method, params };
    const data = `Content-Length: ${Buffer.byteLength(JSON.stringify(msg))}\r\n\r\n${JSON.stringify(msg)}`;
    this.proc.stdin.write(data);
  }

  private drain(): void {
    while (true) {
      const headerEnd = this.buffer.indexOf("\r\n\r\n");
      if (headerEnd === -1) break;
      const header = this.buffer.substring(0, headerEnd);
      const match = header.match(/Content-Length:\s*(\d+)/i);
      if (!match) {
        this.buffer = this.buffer.substring(headerEnd + 4);
        continue;
      }
      const contentLen = parseInt(match[1], 10);
      const bodyStart = headerEnd + 4;
      if (this.buffer.length < bodyStart + contentLen) break;
      const body = this.buffer.substring(bodyStart, bodyStart + contentLen);
      this.buffer = this.buffer.substring(bodyStart + contentLen);
      try {
        const resp: JsonRpcResponse = JSON.parse(body);
        const pending = this.pending.get(resp.id);
        if (pending) {
          this.pending.delete(resp.id);
          pending.resolve(resp);
        }
      } catch (err) {
        console.error(`[mcp-bridge:${this.name}] failed to parse response:`, err);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Manifest loading (global + project-level)
// ---------------------------------------------------------------------------

function loadManifest(cwd: string): McpManifest {
  const manifests: McpServerEntry[] = [];

  // Global manifest: ~/.pi/agent/mcp-manifest.json
  const globalPath = join(homedir(), ".pi", "agent", "mcp-manifest.json");
  try {
    const raw = readFileSync(globalPath, "utf8");
    const parsed = JSON.parse(raw) as McpManifest;
    if (parsed.servers) manifests.push(...parsed.servers);
  } catch {
    console.error("[mcp-bridge] No global manifest found at", globalPath);
  }

  // Project-level manifest: <cwd>/.pi/mcp-manifest.json
  const projectPath = join(cwd, ".pi", "mcp-manifest.json");
  try {
    const raw = readFileSync(projectPath, "utf8");
    const parsed = JSON.parse(raw) as McpManifest;
    if (parsed.servers) {
      // Prefix project server names to avoid collisions with global servers
      for (const server of parsed.servers) {
        manifests.push({
          ...server,
          name: server.name.startsWith("project:") ? server.name : `project:${server.name}`,
        });
      }
      // Suppress — project manifest loaded silently
    }
  } catch {
    // No project manifest — this is normal, don't warn
  }

  return { servers: manifests };
}

// ---------------------------------------------------------------------------
// Extension entry point
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI): void {
  const transports = new Map<string, StdioTransport>();
  const toolToTransport = new Map<string, StdioTransport>();
  let started = false;

  // Connect to a single MCP server and register its tools.
  // Errors are caught and logged — never block the session.
  async function connectServer(entry: McpServerEntry): Promise<void> {
    if (entry.type === "remote") {
      // Remote/streamable HTTP MCP servers not yet supported by this bridge.
      return;
    }
    const transport = new StdioTransport(
      entry.name,
      entry.command ?? "npx",
      entry.args ?? [],
      entry.env ?? {},
    );
    try {
      await transport.start();
      transports.set(entry.name, transport);
      const tools = await transport.listTools();
      for (const tool of tools) {
        toolToTransport.set(tool.name, transport);
        const mcpToolName = tool.name;
        const mcpTransport = transport;
        pi.registerTool(
          defineTool({
            name: `mcp__${entry.name}__${tool.name}`,
            label: `MCP: ${tool.name}`,
            description: tool.description ?? `MCP tool from ${entry.name}: ${tool.name}`,
            parameters: (tool.inputSchema as any) ?? Type.Object({}),
            async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
              const result = await mcpTransport.callTool(mcpToolName, params as Record<string, unknown>);
              return {
                content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
              };
            },
          }),
        );
      }
    } catch (err) {
      // Suppress — MCP server failures don't need TUI noise.
      // Tools simply won't be available if the server is down.
    }
  }

  // --- Startup: load manifests and spawn servers in background ---
  // Fire-and-forget: never block the session_start event.
  pi.on("session_start", (_event, _ctx) => {
    if (started) return;
    started = true;
    const manifest = loadManifest(_ctx.cwd);
    // Connect all servers in parallel, don't await
    Promise.all(manifest.servers.map((entry) => connectServer(entry)));
  });

  // --- Shutdown: kill all spawned servers ---
  pi.on("session_end", async (_event, _ctx) => {
    started = false;
    for (const [, transport] of transports) {
      await transport.stop();
    }
    transports.clear();
    toolToTransport.clear();
  });
}
