# Imports all NixOS modules.
{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./environment.nix
    ./gaming.nix
    ./sddm.nix
    ./graphics.nix
    ./hyprland.nix
    ./niri.nix
    ./i18n.nix
    ./libinput.nix
    ./networking.nix
    ./nix-ld.nix
    ./nix.nix
    ./timezone.nix
    ./tor.nix
    ./upower.nix
    ./users.nix
    ./xserver.nix
    ./nh.nix
    ./monitoring.nix
    ./xdg-desktop-portal.nix
    ./cleanup.nix
    ./browser-deps.nix
    ./stability.nix
    ./virtualisation.nix
    ./mullvad.nix
    ./security.nix
    ./tailscale.nix
    ./bitwarden.nix
    ./nginx.nix
    ./postgresql.nix
    ./sandboxing.nix
    ./macchanger.nix
    ./dnscrypt-proxy.nix
    ./flatpak.nix
  ];
}